ESAPI.Validator=org.owasp.esapi.reference.DefaultValidator
ESAPI.Encoder=org.owasp.esapi.reference.DefaultEncoder
ESAPI.HTTPUtilities=org.owasp.esapi.reference.DefaultHTTPUtilities
ESAPI.Logger=com.fis.ist.esapi.ESAPILogFactory
ESAPI.Logger=com.fis.ist.log.ISTESAPILoggerFactory
ESAPI.printProperties=true
# Validation
# Validator.SafeString=^[\p{L}\p{N}.]{0,1024}$
# Validator.Email=^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\\.[a-zA-Z]{2,4}$
# Validator.IPAddress=^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
# Validator.hostname=^([A-Za-z\\-_.]+)|([0-9. ]{1,15})$
Validator.URL=^(ht|f)tp(s?)\\:\\/\\/[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z])*(:(0-9)*)*(\\/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'\\/\\\\\\+=&amp;%\\$#_]*)?$
# Validator.CreditCard=^(\\d{4}[- ]?){3}\\d{4}$
# Validator.SSN=^(?!000)([0-6]\\d{2}|7([0-6]\\d|7[012]))([ -]?)(?!00)\\d\\d\\3(?!0000)\\d{4}$

# Validators used by ESAPI
# Validator.AccountName=^[a-zA-Z0-9]{3,20}$
# Validator.SystemCommand=^[a-zA-Z\\-\\/]{0,64}$
# Validator.RoleName=^[a-z]{1,20}$

Validator.Redirect=^/?[A-Za-z0-9._-]+(\\?.*)?$
Validator.RelativeURL=^[A-Za-z0-9._-]+(\\?.*)?$

# used for text in an HTML element
Validator.SafeHTMLText=^[a-zA-Z0-9++/_ !.,:-]*$

# Global HTTP Validation Rules
# Values with Base64 encoded data (e.g. encrypted state) will need at least [a-zA-Z0-9\/+=]
Validator.HTTPParameterName=^[a-zA-Z0-9_]{0,32}$
Validator.HTTPParameterValue=^[a-zA-Z0-9.\\-\\/+=_ ]*$
Validator.HTTPCookieName=^[a-zA-Z0-9\\-_]{0,32}$
Validator.HTTPCookieValue=^[a-zA-Z0-9\\-\\/+=_ ]*$
Validator.HTTPHeaderName=^[a-zA-Z0-9\\-_]{0,32}$
Validator.HTTPHeaderValue=^[a-zA-Z0-9()\\-=\\*\\.\\?;,+\\/:&_ ]*$

Validator.FileName=^[a-zA-Z0-9._-]{0,255}$
Validator.DirectoryName=^[a-zA-Z0-9:./_-]{0,255}$
Validator.RelativePathname=^[^/][a-zA-Z0-9:./_-]{0,255}$

Encoder.AllowMultipleEncoding=false
Encoder.AllowMixedEncoding=false
Encryptor.CipherTransformation=AES/CBC/PKCS5Padding
Encryptor.CharacterEncoding=UTF-8

HttpUtilities.ResponseContentType=text/html; charset=UTF-8
HttpUtilities.MaxHeaderSize=4096
HttpUtilities.MaxUploadFileBytes=10
HttpUtilities.maxRedirectLength=512

Logger.ApplicationName=IST-Switch
Logger.LogEncodingRequired=false
Logger.LogApplicationName=false
Logger.LogServerIP=false


# Intrusion Detection
#
# Each event has a base to which .count, .interval, and .action are added
# The IntrusionException will fire if we receive "count" events within "interval" seconds
# The IntrusionDetector is configurable to take the following actions: log, logout, and disable
#  (multiple actions separated by commas are allowed e.g. event.test.actions=log,disable
#
# Custom Events
# Names must start with "event." as the base
# Use IntrusionDetector.addEvent( "test" ) in your code to trigger "event.test" here
#
# You can also disable intrusion detection completely by changing
# the following parameter to true
#
DisableIntrusionDetection=false

event.test.count=2
event.test.interval=10
event.test.actions=disable,log

# Exception Events
# All EnterpriseSecurityExceptions are registered automatically
# Call IntrusionDetector.getInstance().addException(e) for Exceptions that do not extend EnterpriseSecurityException
# Use the fully qualified classname of the exception as the base

# any intrusion is an attack
org.owasp.esapi.errors.IntrusionException.count=1
org.owasp.esapi.errors.IntrusionException.interval=1
org.owasp.esapi.errors.IntrusionException.actions=log,disable,logout

# for test purposes
org.owasp.esapi.errors.IntegrityException.count=10
org.owasp.esapi.errors.IntegrityException.interval=5
org.owasp.esapi.errors.IntegrityException.actions=log,disable,logout

# rapid validation errors indicate scans or attacks in progress
# org.owasp.esapi.errors.ValidationException.count=10
# org.owasp.esapi.errors.ValidationException.interval=10
# org.owasp.esapi.errors.ValidationException.actions=log,logout

# sessions jumping between hosts indicates a session hijacking
org.owasp.esapi.errors.AuthenticationHostException.count=2
org.owasp.esapi.errors.AuthenticationHostException.interval=10
org.owasp.esapi.errors.AuthenticationHostException.actions=log,logout

IntrusionDetector.Disable=false
