# default values (to be overridden)
# $Id$

do_entitlement=true
do_preload=false
do_qtp=false
do_flexmonkey=false

ist.default_page_size=1
flex.ist.default_page_size=${ist.default_page_size}
ist.authentication=oassrv
flex.ist.authentication=${ist.authentication}
ist.launchapplication=_self
ist.ssl.use_ssl=n
ist.ssl.use_was_ssl=n
ist.ssl.need_server_auth=y
ist.ssl.verify_hostname=n
ist.ssl.ks_pass=
ist.ssl.km_pass=${ist.ssl.ks_pass}
 
ist.authenticator.use_ssl=${ist.ssl.use_ssl}
ist.authenticator.use_was_ssl=${ist.ssl.use_was_ssl}
ist.authenticator.was_ssl_alias=${ist.ssl.was_ssl_alias}
ist.authenticator.keystore=${ist.ssl.keystore}
ist.authenticator.truststore=${ist.ssl.truststore}
ist.authenticator.keystore_password=${ist.ssl.ks_pass}
ist.authenticator.truststore_password=${ist.ssl.ts_pass}
ist.authenticator.need_server_auth=${ist.ssl.need_server_auth}
ist.authenticator.verify_hostname=${ist.ssl.verify_hostname}
ist.authenticator.use_rest_api=false

ist.entitlement.use_ssl=${ist.ssl.use_ssl}
ist.entitlement.use_was_ssl=${ist.ssl.use_was_ssl}
ist.entitlement.was_ssl_alias=${ist.ssl.was_ssl_alias}
ist.entitlement.keystore=${ist.ssl.keystore}
ist.entitlement.truststore=${ist.ssl.truststore}
ist.entitlement.keystore_password=${ist.ssl.ks_pass}
ist.entitlement.truststore_password=${ist.ssl.ts_pass}
ist.entitlement.need_server_auth=${ist.ssl.need_server_auth}
ist.entitlement.verify_hostname=${ist.ssl.verify_hostname}

ist.cfgsvc.log=form_audit
ist.cfgsvc.enableMerge=y
ist.cfgsvc.nodemgrTimeout=60
ist.cfgsvc.supported_profiles=switch,balancer,icm
ist.cfgsvc.OPRODUCT_ROOT=${log.property.protected_directory_path}/cfgsvc
ist.cfgsvc.OSITE_ROOT=${log.property.protected_directory_path}/cfgsvc/ositeroot
ist.cfgsvc.ISTDIR==${log.property.protected_directory_path}/istdir
ist.cfgsvc.use_ssl=${ist.ssl.use_ssl}
ist.cfgsvc.use_was_ssl=${ist.ssl.use_was_ssl}
ist.cfgsvc.was_ssl_alias=${ist.ssl.was_ssl_alias}
ist.cfgsvc.keystore=${ist.ssl.keystore}
ist.cfgsvc.truststore=${ist.ssl.truststore}
ist.cfgsvc.keystore_password=${ist.ssl.ks_pass}
ist.cfgsvc.truststore_password=${ist.ssl.ts_pass}
ist.cfgsvc.need_server_auth=${ist.ssl.need_server_auth}
ist.cfgsvc.verify_hostname=${ist.ssl.verify_hostname}

ist.istmon.refresh_rate=120
ist.istmon.supported_profiles=switch,balancer,icm
ist.istmon.ntimeout=30
ist.istmon.formaudit=n
ist.istmon.waiting_time=45
ist.istmon.use_ssl=${ist.ssl.use_ssl}
ist.istmon.use_was_ssl=${ist.ssl.use_was_ssl}
ist.istmon.was_ssl_alias=${ist.ssl.was_ssl_alias}
ist.istmon.keystore=${ist.ssl.keystore}
ist.istmon.truststore=${ist.ssl.truststore}
ist.istmon.keystore_password=${ist.ssl.ks_pass}
ist.istmon.truststore_password=${ist.ssl.ts_pass}
ist.istmon.need_server_auth=${ist.ssl.need_server_auth}
ist.istmon.verify_hostname=${ist.ssl.verify_hostname}

ist.backoffice.timeout=60

ist.formaudit.keep=10
ist.genlog =n
flex.genlog=${ist.genlog}


ist.tokenizer.timeout=5
ist.tokenizer.mode=echo
ist.database=oracle
ist.single_app_auto_popup=n
flex.do_change_password=y

ist.authenticator.host=10.74.169.49
ist.authenticator.port=8701
ist.entitlement.host=10.74.169.49
ist.entitlement.port=8703

#For development (eclipse) use below
#ist.application.ng.url=http\://localhost\:4200/IST-Switch/index.html
 
#For WAR deployment use this (remove the # in the next line and comment the eclipse property above)
#ist.application.ng.url=ng-main.html

ist.numberOfDaysToExpiry=7

ist.application.textinput.chars=A-Za-z 0-9*\\-\\_\\\\\/()?.,#%:!+=&amp;@$
flex.application.textinput.chars=A-Za-z 0-9*\\-\\_\\\\\/()?.,#%:!+=&amp;@$

#Default values for IdP open id connect protocol
ist.oidc.provider_id=${ist.oidc.client_id}
ist.oidc.registration_id=${ist.oidc.client_id}
ist.oidc.redirection_uri=${ist.root_url}/login/oauth2/code/${ist.oidc.registration_id}
ist.oidc.grant_type=authorization_code
ist.oidc.scope=openid
ist.oidc.authentication_method=post
ist.oidc.mapped_user.case_sensitive=y
ist.oidc.mapped_last_login_date_attr=LastLoginDate
