#$ delimitor used for  OR condition
#~ delimitor used for  AND condition in forming the SQL query
#^ delimitor used for datatype difference between parent and child tables

# Removed IST_TXNCLASS|INSTITUTION_ID, ALT_MERCHANT_ID|INSTITUTION_ID

#General Setup Screens
#INSTITUTION =ATMGROUP|INSTITUTIONID,ATMSDESC|INSTITUTIONID,ATMSUPCARD|INSTITUTIONID,INST_RKM_CERT|INSTITUTIONID,INST_RKM_CERT_REQ|INSTITUTIONID,INST_RKM_PK|INSTITUTIONID,ATMCASSETTELIST|INSTITUTIONID,ATMDISPENSECFG|INSTITUTIONID,ATMDISPENSEITEM|INSTITUTIONID,ATMDISPENSELIST|INSTITUTIONID,ATMEJCAPTURE|INSTITUTIONID,ATMFITENTRY|INSTITUTIONID,ATMFIT|INSTITUTIONID,ATMFITLIST|INSTITUTIONID,ATM|INSTITUTIONID,ATMSTATETABLEVER|INSTITUTIONID,DEV_SURCHARGE|INSTITUTIONID,SURCHARGE_RATE|INSTITUTIONID,ATMFITSELECT|INSTITUTIONID,ATMKEYCHG|INSTITUTIONID,ATMLOG|INSTITUTIONID,ATMMONGP|INSTITUTIONID,ATMMONNET|INSTITUTIONID,ATMMONSYS|INSTITUTIONID,ATMMONUNIT|INSTITUTIONID,ATMTOT|INSTITUTIONID,DEVICEKEY|INSTITUTIONID,IST_CARDTYPE|INSTITUTION_ID,IST_ACCOUNT|INSTITUTION_ID,IST_ACCUM_AMOUNT|INSTITUTION_ID,IST_ACCUM_COUNT|INSTITUTION_ID,IST_BRANCH|INSTITUTION_ID,IST_CARD|INSTITUTION_ID,IST_CUSTOMER|INSTITUTION_ID,IST_ENTITY_REL|INSTITUTION_ID,IST_ISS_ENTITY|INSTITUTION_ID,IST_LIMIT_AMOUNT|INSTITUTION_ID,IST_LIMIT_COUNT|INSTITUTION_ID,IST_LOGHIST|INSTITUTION_ID,IST_PINHIST|INSTITUTION_ID,IST_PIN|INSTITUTION_ID,IST_TXNCLASS_DESC|INSTITUTION_ID,IST_TXNDESC|INSTITUTION_ID,INST_BUSINESS_DAY|INSTITUTION_ID,ACQ_ENTITY_CONFIG|INSTITUTION_ID,ACQ_ENTITY|INSTITUTION_ID,ALLOWANCE|INSTITUTION_ID,POS_TERM_KEYS|INSTITUTION_ID,ENTITY_LEVEL|INSTITUTION_ID,LOG_EXT_FILE|INSTITUTION_ID,LOG_EXTRACT|INSTITUTION_ID,POS_BATCH|INSTITUTION_ID,TERMINAL_BDK|INSTITUTION_ID,TERMINAL|INSTITUTION_ID,POSLOG_ERR|INSTITUTION_ID,SWITCH_FIELD_VALUE_CTRL|INSTITUTION_ID,BLOCK_BY_BRAND|INSTITUTIONID,BINROUTE|INSTITUTIONID,PINVERPARM|INSTITUTIONID,SHCKEYS|INSTITUTIONID,SHCBIN|INSTITUTIONID,ISS_PROFILE|TXNSRC,ISS_PROFILE|TXNDEST,SHC600LOG|TXNSRC,SHC600LOG|TXNDEST,ACQ_ENTITY|INSTITUTION_ID,INST_PROFILE|INST_ID,CARD_SCHEME|CS_INST_ID,ISTCURR|BIN,ISTCURSPR|BIN

#LANGUAGE=INSTITUTION|LANGUAGE_CODE,POS_SHC2POS_RC|LANGUAGE_CODE,ACQ_ENTITY|LANGUAGE_CODE,IST_CARD|LANGUAGE_CODE,IST_CARDTYPE|DEFAULT_LANG_CODE

#CURRENCY_CODE=COUNTRY|CURR_CODE,INSTITUTION|INST_CURR_CODE,IST_ACCOUNT|CURRENCY_CODE^INTEGER,POS_BATCH|CURRENCY_CODE,ISTCURR|CURRENCY^INTEGER,IST_LIMIT_AMOUNT|CURRENCY_CODE^INTEGER,IST_LIMIT_COUNT|CURRENCY_CODE^INTEGER,IST_LOGHIST|ACQ_CURRENCY_CODE^INTEGER,ATMCASSETTECFG|CURRENCY^INTEGER,POS_TERM_CAP_TRANS|ACQ_CURRENCY_CODE^INTEGER,ATM|CURRENCY^INTEGER,SHCBIN|CURRENCY_CODE^INTEGER,ACQ_PROFILE|CURR_CODE^CHAR(40),TERMINAL|DEFAULT_CURR_CD

#CURRENCY_CODE_OLD=COUNTRY|CURR_CODE,INSTITUTION|INST_CURR_CODE,ATM|CURRENCYA^INTEGER,ATM|CURRENCYB^INTEGER,ATM|CURRENCYC^INTEGER,ATM|CURRENCYD^INTEGER,ATM|CURRENCYE^INTEGER,ATM|CURRENCYF^INTEGER,ATM|CURRENCYG^INTEGER,ATM|CURRENCYH^INTEGER,SHCBIN|CURRENCY_CODE^INTEGER

#COUNTRY=POS_TERM_CAP_ADD|DEST_COUNTRY_CD^CHAR(3),POS_TERM_CAP_CHIP|TERM_COUNTRY_CODE^NUMBER,SHC600LOG|ACQ_COUNTRY^INTEGER,SHCBIN|COUNTRY_CODE^INTEGER,SHCEXTBINDB|COUNTRY_CODE^INTEGER,SHCLOG|ACQ_COUNTRY^INTEGER,MASTER_ADDRESS|CNTRY_CODE^CHAR(3),MASTER_CONTACT|CNTRY_CODE^CHAR(3),PROVINCE|CNTRY_CODE^CHAR(3)

#PROVINCE=MASTER_ADDRESS|CNTRY_CODE~PROV_STATE_ABBREV^CHAR(3)~CHAR(3),MASTER_CONTACT|CNTRY_CODE~PROV_STATE_ABBREV^CHAR(3)~CHAR(3)

#MERCHANT_TYPE=MCC|CARD_SCHEME~MERCHANT_TYPE^CHAR(2)~VARCHAR2(4)


#ATM Group setup screens
ATMGROUP=ATM_RKM_PK|GROUP_NAME~INSTITUTIONID,ATM_RKM_CERT|GROUP_NAME~INSTITUTIONID,ATMCOUNTERS|GROUP_NAME~INSTITUTIONID,ATMSRV_ROUTE|GROUP_NAME~INSTITUTIONID,ATMSTATUS|GROUP_NAME~INSTITUTIONID,MCPATMSTA|GROUP_NAME~INSTITUTIONID,MCPATMTOT|GROUP_NAME~INSTITUTIONID,ATMCASSETTECOUNTER|GROUP_NAME~INSTITUTIONID,ATMCASSETTELIST|GROUP_NAME~INSTITUTIONID,ATMAVAIL|GROUP_NAME~INSTITUTIONID,ATMLOG|GROUP_NAME~INSTITUTIONID,ATMMONGP|GROUP_NAME~INSTITUTIONID,ATMMONUNIT|GROUP_NAME~INSTITUTIONID,ATM_EJOURNAL_LOG|GROUP_NAME~INSTITUTIONID,ATMBAL|GROUP_NAME~INSTITUTIONID,ATMFITSELECT|GROUP_NAME~INSTITUTIONID,ATMDISPENSELIST|GROUP_NAME~INSTITUTIONID,ATMFITLIST|GROUP_NAME~INSTITUTIONID,DEV_SURCHARGE|GROUP_NAME~INSTITUTIONID,SURCHARGE_RATE|GROUP_NAME~INSTITUTIONID,ATMTOTALS|GROUP_NAME~INSTITUTIONID,ATM|GROUP_NAME~INSTITUTIONID,ATMDESKEYS|GROUP_NAME~INSTITUTIONID,ATMDEVICESTATE|GROUP_NAME~INSTITUTIONID,ATMEJCAPTURE|GROUP_NAME~INSTITUTIONID,MCPATMCFG|GROUP_NAME~INSTITUTIONID

CARD_SCHEME=IST_CARD_PRODUCT|CARD_SCHEME,MERCHANT_TYPE|CARD_SCHEME,ALT_MERCHANT_ID|CARD_SCHEME

SHCBIN=BINROUTE|INSTITUTIONID~USERBINID,CAMKEYS|INSTITUTIONID~USERBINID,INST_PROFILE|INST_ID~USERBIN_ID^CHAR(10)~CHAR(10),ISS_PROFILE|ISS_INST_ID~ISS_USERBIN_ID^CHAR(10)~CHAR(10),ACQ_PROFILE|ACQ_INST_ID~ACQ_USERBIN_ID^CHAR(10)~CHAR(10)

IST_CARD_PRODUCT=SHCEXTBINDB|CARDPRODUCT^CHAR(10)

ATMFITENTRY=ATMFIT|FIT_ENTRY_ID~INSTITUTIONID
ATMFITLIST=ATM|FIT_LIST_ID~INSTITUTIONID,ATMFIT|FIT_LIST_ID~INSTITUTIONID
ATM=ATMAVAIL|GROUP_NAME-LPAD~INSTITUTIONID~UNIT,ATMSTATUS|GROUP_NAME-LPAD~INSTITUTIONID~UNIT,ATMTOTALS|GROUP_NAME-LPAD~INSTITUTIONID~UNIT,MCPATMSTA|GROUP_NAME-LPAD~INSTITUTIONID~UNIT,ATM_RKM_CERT|GROUP_NAME~INSTITUTIONID~UNIT,ATMCOUNTERS|GROUP_NAME-LPAD~INSTITUTIONID~UNIT,MCPATMTOT|GROUP_NAME-LPAD~INSTITUTIONID~UNIT,ATMMONUNIT|GROUP_NAME~INSTITUTIONID~UNIT^CHAR(10)~VARCHAR2(10)~INTEGER
#ATMMONUNIT|GROUP_NAME~INSTITUTIONID~UNIT^CHAR(10)~VARCHAR2(10)~INTEGER,SHCLOG|INSTITUTIONID~TERMID
#ATM=ATMAVAIL|GROUP_NAME~INSTITUTIONID~UNIT,ATMSTATUS|GROUP_NAME~INSTITUTIONID~UNIT,ATMTOTALS|GROUP_NAME~INSTITUTIONID~UNIT,MCPATMSTA|GROUP_NAME~INSTITUTIONID~UNIT,ATMMONUNIT|GROUP_NAME~INSTITUTIONID~UNIT^CHAR(10)~VARCHAR2(10)~INTEGER

#SHCKEYS=INST_PROFILE|KEYPARAM

#ATM=ATMTOTALS,ATMCOUNTERS,ATMCASSETTECOUNTERS,ATMAVAIL,ATM_EJOURNAL_LOG,ATM_RKM_CERT,ATM_RKM_PK,ATMSTATUS,ATM_EJOURNAL_LOG -- column mapping to be done.

ENT_USER=ENT_OBJ_PERM|RQSTING_ENT_OBJ_ID,ENT_OBJGRP_MEMBER|ENT_OBJECT_ID

ENT_USER_PROFILE=ENT_OBJ_PERM|RQSTING_ENT_OBJ_ID,ENT_OBJGRP_MEMBER|ENT_OBJECT_ID

ENT_OBJECT=ENT_GRP_PERM|RQSTED_ENT_OBJ_ID,ENT_OBJGRP_MEMBER|ENT_OBJECT_ID,ENT_OBJ_PERM|RQSTED_ENT_OBJ_ID

ENT_GROUP=ENT_GRP_PERM|RQSTING_ENT_GRP_ID,ENT_OBJGRP_MEMBER|ENT_GROUP_ID

ENT_CLASS=ENT_OBJECT|ENT_CLASS_ID

#Pos 
POS_MSG_BRAND=POSLOG_ERR|POS_MSG_BRAND,POS_SHC2POS_RC|POS_MSG_BRAND,TERMINAL|POS_MSG_BRAND

ENTITY_LEVEL=ACQ_ENTITY|ENTITY_LEVEL~INSTITUTION_ID

ALLOWANCE=ACQ_ENTITY|ALLW_ID~INSTITUTION_ID,ALLW_FLOOR_LIM|ALLW_ID~INSTITUTION_ID,TERMINAL|ALLW_ID~INSTITUTION_ID

POS_TERM_TYPE=TERMINAL|POS_TERMINAL_TYPE

TERMINAL=LOG_EXTRACT|INSTITUTION_ID~TERM_RECORD_SEQ,POS_BATCH|INSTITUTION_ID~TERM_RECORD_SEQ,POSLOG_ERR|INSTITUTION_ID~TERM_RECORD_SEQ^CHAR(10)~NUMBER(15),POS_TERM_KEYS|INSTITUTION_ID~TERM_RECORD_SEQ

POS_TERM_KEYS=POS_BATCH|INSTITUTION_ID~ENTITY_ID~TERM_RECORD_SEQ~TERMID,POSLOG_ERR|INSTITUTION_ID~ENTITY_ID~TERM_RECORD_SEQ~TERMID^CHAR(10)~CHAR(30)~NUMBER(15)~CHAR(8)

ACQ_ENTITY=POS_BATCH|ENTITY_ID~INSTITUTION_ID,TERMINAL|OWNER_ENTITY_ID~INSTITUTION_ID,POS_TERM_KEYS|OWNER_ENTITY_ID~INSTITUTION_ID,POSLOG_ERR|ENTITY_ID~INSTITUTION_ID^CHAR(30)~CHAR(10),LOG_EXT_FILE|OWNER_ENTITY_ID~INSTITUTION_ID,ACQ_ENTITY=LOG_EXTRACT|OWNER_ENTITY_ID~INSTITUTION_ID




#Table screen mapping
# GENERAL Set up
INSTITUTION@screen =Institution entity
LANGUAGE@screen = Languages
CURRENCY_CODE@screen = Currency
ISTCURR@screen =  Currency Rates
ISTCURSPR@screen = Currency Spread
COUNTRY@screen =Country
PROVINCE@screen = Province
MERCHANT_TYPE@screen = Merchant Type
MCC@screen = MCC
GLOBAL_VALUE_CTRL@screen = Global Value Control
GLOBAL_SEQ_CTRL@screen = Global Sequence Control
SEQ_CTRL@screen = Sequence Control
SWITCH_FIELD_VALUE_CTRL@screen = Field Value Control
CARD_SCHEME@screen = Card Scheme
INST_BUSINESS_DAY@screen = Institution Business Day
MASTER_ADDRESS@screen = Institution Address or Acquiring Address
MASTER_CONTACT@screen = Institution Contact or Acquiring Contact 

#SHC screens

IST_CARD_PRODUCT@screen =IST Card Product
RC_MAPPING@screen = Response Code Mapping
PINVERPARM@screen =  PIN Verification Parameters
SHCKEYS@screen = Network Security Keys
SHCBIN@screen =  BIN
#EMVSTIPCHK@screen =SHC >BIN > BIN Setup > BIN Setup Detail(EMV Security tab) --This is Part of BIN Setup screen
#CAMKEYS@screen = SHC >BIN >BIN Setup>BIN Setup Detail> EMV Issuer Keys --This is Part of BIN Setup screen 
#ISTTRIG@screen  = SHC >BIN > BIN Setup > BIN Setup Detail(Security tab)--This is Part of BIN Setup screen 
INST_PROFILE@screen = Institution Profile
BINROUTE@screen  = Bin Route
ISS_PROFILE@screen = Issuer Profile
ACQ_PROFILE@screen = Acquirer Profile
SHCEXTBINDB@screen =BIN Range Routing
BLOCK_BY_BRAND@screen = Block By Brand
SHCCARD@screen = Hot Cards
HOTRANGE@screen = Hot Card Ranges
SHCLOG@screen = SHC Transaction Log
SHC600LOG@screen = SHC600 Log


# Authorization Screens

IST_ACCUM_AMOUNT@screen = Authorization Limit Amount
IST_ACCUM_COUNT@screen = Authorization Limit Count
IST_BRANCH@screen =  Authorization Branch
IST_PIN_TYPE@screen = Authorization PIN Type
IST_PIN_METHOD@screen =  Authorization PIN Method
IST_TXNDESC@screen = Authorization Transaction Description
#IST_TXNCLASS@screen = Authorization Transaction Class
IST_TXNCLASS_DESC@screen = Authorization Transaction Class Description
IST_STATUS@screen = Authorization Status
IST_LIMIT_AMOUNT@screen = Authorization Limit Amount
IST_LIMIT_COUNT@screen = Authorization Limit Count
IST_CARDTYPE@screen = Authorization Card Type
IST_ISS_ENTITY@screen = Authorization Issuing Entity 
IST_ACCOUNT@screen = Authorization Account
IST_CUSTOMER@screen = Authorization Customer
IST_CARD@screen = Authorization Card
IST_ENTITY_REL@screen = Authorization Entity Relationship
IST_LOGHIST@screen = Authorization Log  History
IST_PINHIST@screen =Authorization PIN Change History

# POS screens
POS_OPEN_HOUR@screen  = POS Open Hour
POS_MSG_BRAND@screen = POS Message Brand
POS_SHC2POS_RC@screen = POS Response Code Map
ENTITY_LEVEL@screen = Acquiring Entity Level
ALLOWANCE@screen = Allowance
ALLW_FLOOR_LIM@screen=Allowance Detail-Floor Limits Tab
#ALLW_FLOOR_LIM@screen = POS >  General POS  Setup >Allowance Detail
ACQ_ENTITY@screen = Acquiring Entity
ACQ_ENTITY_CONFIG@screen=Acquirer Entity Configuration entity
#ALT_MERCHANT_ID@screen = POS >  Acquiring Entity
POS_TERM_TYPE@screen = POS Terminal Type
TERMINAL@screen = POS Terminal
POS_TERM_KEYS@screen =POS Terminal Keys
TERMINAL_BDK@screen = POS Terminal BDK
POS_BATCH@screen = POS Batch
POS_TERM_CAP_TRANS@screen  = POS Terminal Capture Transaction
POS_TERM_CAP_ADD@screen = POS Terminal Capture Transaction
POS_TERM_CAP_AIR@screen = POS Terminal Capture Transaction
POS_TERM_CAP_CHIP@screen = POS Terminal Capture Transaction
POS_REFNUM@screen = POS Reference Number Log
FILE_BATCHTOTAL@screen = POS File Batch
LOG_EXTRACT@screen =POS Log Extract
LOG_EXT_FILE@screen =POS Log Extract File
POSLOG_ERR@screen  = POS Error Log

#ATM screens
ATMSUPCARD@screen = ATM Supervisor Cards
ATMAVAIL@screen = ATM Availability 
ATMSDESC@screen = ATM Status Description
ATMFITENTRY@screen = ATM FIT Entry
ATMGROUP@screen = ATM Group
ATM_RKM_PK@screen =ATM Remote Key Management
ATM_RKM_CERT@screen =ATM Remote Key Management
INST_RKM_CERT@screen=Institution Remote Key Management
INST_RKM_CERT_REQ@screen =Institution Remote Key Management
INST_RKM_PK@screen =Institution Remote Key Management
ATM@screen=ATM 
# For OLD ATM Project following entries are add specifically country code
ATM_1@screen=ATM
ATM_2@screen=ATM
ATM_3@screen=ATM
ATM_4@screen=ATM
ATM_5@screen=ATM
ATM_6@screen=ATM
ATM_7@screen=ATM
#ATMDEVICESTATE@screen=ATM 
#ATMSRV_ROUTE@screen=ATM 
#ATMDESKEYS@screen=ATM 
ATMCASSETTECFG@screen=ATM Cassettes
ATMCASSETTELIST@screen=ATM Cassettes
ATMFIT@screen=ATM FIT List
ATMFITLIST@screen=ATM FIT List
ATMDISPENSECFG@screen =Dispense Tables
ATMDISPENSEITEM@screen =Dispense Tables
ATMDISPENSELIST@screen=Dispense Tables
SURCHARGE_RATE@screen=ATM Surcharges
DEV_SURCHARGE@screen =ATM Surcharges
ATMSTATUS@screen=ATM Status
ATM_EJOURNAL_LOG@screen=ATM EJournal
ATMEJCAPTURE@screen=ATM Electronic Journal
ATMCOUNTERS@screen=ATM Totals and Balance
ATMCASSETTECOUNTER@screen=ATM Totals and Balance
ATMTOTALS@screen=ATM Totals and Balance
MCPATMSTA@screen=ATM Totals and Balance 
MCPATMTOT@screen=ATM Totals and Balance

#ist.integrity.msg=Integrity Constraint Violated - Child record found 
ist.integrity.msg=ER175

#User Administration

ENT_OBJ_PERM@screen = User Permissions
ENT_OBJGRP_MEMBER@screen = User Group/Entitlement Group Members
ENT_OBJECT@screen = Entitlement Object
ENT_GRP_PERM@screen = Group Permission
ENT_PERMISSION@screen= Entitlement Permission









