# Logger configuration
# Each entry configures a logger based on the location of the class(es)
# log.level.<package>
log.level.root=ERROR
# T21
log.level.com.efunds.t21=WARN

# IST
log.level.com.fis.ist=ERROR
#log.level.com.fis.ist.ent=ERROR
#log.level.com.fis.ist.spring=ERROR
#log.level.com.fis.ist.springsecurity=ERROR
#log.level.com.fis.ist.springsecurity.oentsrv=ERROR
#log.level.com.fis.ist.cfg.ConfigParams=ERROR
#log.level.com.fis.ist.cfg.ConfigListener=ERROR
#log.level.com.fis.ist.common.BlazeLogger=ERROR
#log.level.com.fis.ist.services.handler=ERROR
#log.level.com.fis.ist.services.MenuService=ERROR
log.level.com.fis.ist.services.SiteGracefulShutDown=ERROR
log.level.com.fis.ist.services.SiteGracefulStartUp=ERROR
log.level.com.fis.ist.services.SiteShutDown=ERROR

# Entitlement
log.level.com.oasis.ent=WARN

# Authentication
log.level.com.oasis.authentication=ERROR

# Spring
log.level.org.springframework=ERROR
#log.level.org.springframework.security=ERROR
#log.level.org.springframework.security.cas=ERROR
#log.level.org.springframework.web=ERROR
#log.level.org.springframework.beans=ERROR

# Hibernate
log.level.org.hibernate=ERROR
#log.level.org.hibernate.cfg=ERROR
#log.level.org.hibernate.connection=ERROR
#log.level.org.hibernate.dialect=ERROR
#log.level.org.hibernate.engine=ERROR
#log.level.org.hibernate.event=ERROR
#log.level.org.hibernate.exception=ERROR
#log.level.org.hibernate.hql=ERROR
#log.level.org.hibernate.impl=ERROR
#log.level.org.hibernate.jdbc=ERROR
#log.level.org.hibernate.loader=ERROR
#log.level.org.hibernate.mapping=ERROR
#log.level.org.hibernate.persister=ERROR
#log.level.org.hibernate.SQL=ERROR
#log.level.org.hibernate.transaction=ERROR
#log.level.org.hibernate.type=ERROR
#log.level.org.hibernate.util=ERROR

# C3PO pooling
log.level.com.mchange.v2=ERROR
log.level.com.mchange.v2.c3p0=WARN
log.level.com.mchange.v2.resourcepool=WARN

# Quartz scheduler
log.level.org.quartz=WARN

#XML display
log.display_config_xml=false

#TRACE Level
log.config_trace_level=ERROR

# Log Configuration 
log.type=rolling_file
log.file=${protected_directory_path}/logs/${hostname}-${context_root}.log
log.rolling_file_pattern=${log_path}/logs/${hostname}-${context_root}-%d{MM-dd-yyyy}-%i.log.gz
log.pattern=%d [%X{userName}] %-5p %t - [%c{1}]: %m%n
log.rolling_file_size=10M
log.rolling_file_schedule=0 0 0 * * ?
log.append=true