--Employee single page screen
INSERT INTO ENT_OBJECT (ENT_OBJECT_ID, ENT_CLASS_ID, ENT_OBJECT_DESC)VALUES ('5.EMPLISTSP',5, 'Employee single page Form');
INSERT INTO ENT_OBJECT (ENT_OBJECT_ID, ENT_CLASS_ID, ENT_OBJECT_DESC)VALUES ('55.EMPLISTSP.I',55 ,'Employee Single Page Form Insert Action');
INSERT INTO ENT_OBJECT (ENT_OBJECT_ID, ENT_CLASS_ID, ENT_OBJECT_DESC)VALUES ('55.EMPLISTSP.U',55 ,'Employee Single Page Form Update Action');
INSERT INTO ENT_OBJECT (ENT_OBJECT_ID, ENT_CLASS_ID, ENT_OBJECT_DESC)VALUES ('55.EMPLISTSP.Q',55 ,'Employee Single Page Form Query Action');
INSERT INTO ENT_OBJECT (ENT_OBJECT_ID, ENT_CLASS_ID, ENT_OBJECT_DESC)VALUES ('55.EMPLISTSP.D',55 ,'Employee Single Page Form Delete Action');
COMMIT;