CREATE TABLE EMPLOYEE
(
  EMPLOYEE_ID    NUMBER(6) PRIMARY KEY,
  EMP_NAME       VARCHAR2(30 BYTE),
  EMAIL          VARCHAR2(20 BYTE),
  HIRE_DATE      DATE                           NOT NULL,
  SALARY         NUMBER(12,2),
  DEPARTMENT_ID  NUMBER(4)
);